import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/_components/Navbar";
import Footer from "@/_components/Footer";
import { Box } from "@mui/material";
import { ToastContainer } from "react-toastify";
import ThemeRegistry from "./ThemeRegistry";

export const metadata: Metadata = {
  title: "Qashnova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <Box
            sx={{
              position: { xs: "fixed", sm: "unset" },
              top: "0",
              zIndex: "10000",
              width: "100%",
            }}
          >
            <Navbar />
          </Box>
          <Box sx={{ marginTop: { xs: "89px", sm: "unset" } }}>
            {children}
            <Footer />
          </Box>
          <ToastContainer position="top-right" autoClose={3000} />
        </body>
      </ThemeRegistry>
    </html>
  );
}
