// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import LayoutWrapper from "@/_components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Qashnova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <LayoutWrapper>{children}</LayoutWrapper>
        </body>
      </ThemeRegistry>
    </html>
  );
}
